##
## Copyright (c) 2014, Facebook, Inc.
## All rights reserved.
##
## This source code is licensed under the University of Illinois/NCSA Open
## Source License found in the LICENSE file in the root directory of this
## source tree. An additional grant of patent rights can be found in the
## PATENTS file in the same directory.
##

language: cpp

env:
  - BUILD_TYPE="Debug"    TARGET="Linux-X86_64"   REGSGEN="1"
  - BUILD_TYPE="Style"
  - BUILD_TYPE="Debug"    TARGET="Android-ARM"
  - BUILD_TYPE="Debug"    TARGET="Android-ARM64"
  - BUILD_TYPE="Debug"    TARGET="Android-X86"
  - BUILD_TYPE="Debug"    TARGET="Android-X86_64"
  - BUILD_TYPE="Debug"    TARGET="Linux-ARM"
  - BUILD_TYPE="Debug"    TARGET="Linux-X86"
  - BUILD_TYPE="Debug"    TARGET="Linux-X86_64"
  - BUILD_TYPE="Debug"    TARGET="Linux-X86_64"   LLGS_TESTS="1"
  - BUILD_TYPE="Release"  TARGET="Android-ARM"
  - BUILD_TYPE="Release"  TARGET="Android-ARM64"
  - BUILD_TYPE="Release"  TARGET="Android-X86"
  - BUILD_TYPE="Release"  TARGET="Android-X86_64"
  - BUILD_TYPE="Release"  TARGET="Linux-ARM"
  - BUILD_TYPE="Release"  TARGET="Linux-X86"
  - BUILD_TYPE="Release"  TARGET="Linux-X86_64"
  - BUILD_TYPE="Release"  TARGET="Linux-X86_64"   LLGS_TESTS="1"

matrix:
  fast_finish: true

before_install:
  - ./Support/Testing/Travis/before-install.py

install:
  - ./Support/Testing/Travis/install.py

script:
  - ./Support/Testing/Travis/script.sh
