language: cpp

env:
  - TARGET="Linux-ARM"
  - TARGET="Linux-X86"
  - TARGET="Linux-X86_64"

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository -y ppa:linaro-maintainers/toolchain
  - sudo apt-get update
install:
  - sudo apt-get install -y g++-arm-linux-gnueabi g++-4.8-multilib

before_script:
  - mkdir -p build && cd build
  - make -DCMAKE_TOOLCHAIN_FILE="../Support/CMake/Toolchain-${TARGET}.cmake" ..
script:
  - make
